name = "Doors"
license = "MIT"
licenselink = "https://github.com/zzzmisa/hugo-theme-doors/blob/master/LICENSE"
description = "Single page theme for links to your works"

homepage = "https://github.com/zzzmisa/hugo-theme-doors"
demosite = "https://zzzmisa.com"

tags = ["amp", "gallery", "google-analytics", "mobile", "onepage", "one page", "portfolio", "projects", "responsive", "single page" ]
features = ["amp", "google-analytics", "responsive"]

[author]
  name = "zzzmisa"
  homepage = "https://zzzmisa.com"
